## Date range (inclusive) that you want to generate BCs for
startDate: "20180401"
endDate: "20240229"

## A directory with a lot of space where you can write the BCs (and intermediate files)
workDir: "/n/holylfs05/LABS/jacob_lab/Users/nbalasus/v2024-06-IMI-BCs"

## Paths to TROPOMI data and blended TROPOMI+GOSAT data
tropomiDir: "/n/holylfs05/LABS/jacob_lab/Everyone/imi/ch4/tropomi"
blendedDir: "/n/holylfs05/LABS/jacob_lab/Everyone/imi/ch4/blended"

## Conda environment to use, GEOS-Chem environment to use, GEOS-Chem input data path, and partitions to run on
condaEnv: imi_env
condaFile: ~/.bashrc
geosChemEnv: "../../envs/Harvard-Cannon/gcclassic.rocky+gnu12.minimal.env"
geosChemDataPath: "/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData"
partition: huce_cascade,seas_compute,huce_ice

## A restart file for GEOS-Chem for your simulation start date
restartFilePath: "/path/to/restart/file"

# Debug or not?
debug: true
